import streamlit as st
import pandas as pd
import numpy as np
from datetime import time
import datetime



st.title("Fallecidos por COVID-19")

st.caption("En esta página web se realiza el registro diaria de muertes por Covid-19")
text=st



chart_data = pd.DataFrame(
    np.random.randn(20, 3),
    columns=["a", "b", "c"])

st.bar_chart(chart_data)




tittle=st.text_input('Nombre y Apellidos:')
st.write(tittle)

d= st.date_input("Fecha de fallecimiento",datetime.date(2019, 7, 6))
st.write("ingresar fecha de fallecimiento:", d)

choice = st.selectbox("Sexo", ["Femenino","Masculino"])


option = st.selectbox('¿Cómo desearía ser contactado/a?',('Email', 'Teléfono','Whatsapp'))
st.write('Seleccionó:', option)

tittle=st.text_input('Ingrese la opción que eligió')
st.write("Número de teléfono o email de contecto:", tittle)

# -*- coding: utf-8 -*-
"""PROYECTO PROGRA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-GdKL8HLKFka39UNUauwDkSJ2BC5S_PA
"""

!wget https://raw.githubusercontent.com/hilaryscarlett/proyecto-progra/main/fallecidos_covid.csv

import pandas as pd

pd.read_csv("fallecidos_covid.csv")
