# -*- coding: utf-8 -*-
"""PROYECTO PROGRA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-GdKL8HLKFka39UNUauwDkSJ2BC5S_PA
"""

!wget https://raw.githubusercontent.com/hilaryscarlett/proyecto-progra/main/fallecidos_covid.csv

import pandas as pd

pd.read_csv("fallecidos_covid.csv")







